import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import Header from '@/component/element/Header/Header';
import Footer from '@/component/element/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'KinoArea',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
	return (
		<html lang="ru">
		<body className={inter.className}>
		<Header />
		{children}
		<Footer />
		</body>
		</html>
	);
}
